config/routes.rb
Kite::Application.routes.draw do
  resources :venues
  resources :events do
  	collection do
      delete 'destroy_multiple'
    end
    #member do
  	#	get 'fav'
  	#end
  end
  devise_for :users, :controllers => { :sessions => 'sessions' }
  devise_for :hosts#, :skip => :sessions

  root :to => 'categories#index'
  get 'about' => 'pages#about'
  get 'blog' => 'pages#blog'
  get 'help' => 'pages#help'
  get 'list' => 'events#list'
end

app/models/venue.rb
class Venue < ActiveRecord::Base
  attr_accessible :name, :address, :latitude, :longitude

  belongs_to :host
  has_many :events, :dependent => :destroy

  validates :name, :address, :host_id, presence: true
  validates_length_of :name, :address, :maximum => 70
  geocoded_by :address
  after_validation :geocode, :if => :address_changed?
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  before_filter :authenticate_user!, except: [:show]

  def index
    @venues = current_user.venues #only show the user's venues

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @venues }
    end
  end

  def show
    @venue = Venue.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @venue }
    end
  end

  def new
    @url_location = :back
    @venue = current_user.venues.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @venue }
    end
  end

  def edit
    @url_location = venues_path
    @venue = current_user.venues.find(params[:id])
  end

  def create
    @venue = current_user.venues.new(params[:venue])

    respond_to do |format|
      if @venue.save
        format.html { redirect_to({action: "index"}, notice: "Cool. Got it.")}
        format.json { render json: @venue, status: :created, location: @venue }
      else
        format.html { render action: "new" }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @venue = current_user.venues.find(params[:id])

    respond_to do |format|
      if @venue.update_attributes(params[:venue])
        format.html { redirect_to({action: "index"}, notice: update_flash_message)}
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @venue = current_user.venues.find(params[:id])
    @venue.destroy

    respond_to do |format|
      format.html { redirect_to venues_url }
      format.json { head :no_content }
    end
  end
end

app/views/venues/_form.html.erb
<%= simple_form_for(@venue, defaults: { input_html: { class: "form-control" }}) do |f| %>
  <%= f.error_notification %>

  <%= f.input :name %>
  <%= f.input :address %>

  <%= f.input :submit, :wrapper => :bs_submit_button do %>
    <%= f.submit "Add venue", :class => "btn btn-primary" %>
  <% end %>
<% end %>

app/views/venues/_venue_form.html.erb
<%= simple_form_for(@venue, defaults: { input_html: { class: "form-control" }}) do |f| %>
  <%= f.error_notification %>

  <%= f.input :name %>
  <%= f.input :address %>

  <%= f.input :submit, :wrapper => :bs_submit_button do %>
    <%= f.submit "Add venue", :class => "btn btn-primary" %>
  <% end %>
<% end %>

app/views/venues/edit.html.erb
<div class="row form-header">
	<h3 class="col-md-offset-3 col-md-9">Edit your venue</h3>
</div>

<%= render 'venue_form' %>

app/views/venues/index.html.erb
<div class="row form-header form-header-list">
	<h3 class="col-sm-8">Manage your venues</h3>
	<p class="col-sm-4">
		<%= link_to 'Add new event', new_event_path %>&emsp;
		<%= link_to 'Add new venue', new_venue_path %>
	</p>
</div>

<table id="venues-table" class="table table-hover tablesorter">
	<thead>
	  <tr>
	    <th >Name</th>
	    <th>Address</th>
	    <th></th>
	  </tr>
  </thead>
  <tbody>
		<% @venues.each do |venue| %>
		<% edit = edit_venue_path(venue) %>
		  <tr>
		    <td><%= link_to venue.name, edit %></td>
		    <td><%= link_to venue.address, edit %></td>
		    <td>
		    	<%= link_to 'Delete', venue, method: :delete, data: { confirm: 'Are you sure?' } %>
		    </td>
		  </tr>
		<% end %>
	</tbody>
</table>

app/views/venues/new.html.erb
<div class="row form-header">
	<h3 class="col-md-offset-3 col-md-9">Add a new venue</h3>
</div>
<%= render 'venue_form' %>

app/views/venues/show.html.erb
<div class="row">
  <div class="event-div">
    <div class="event-title">
      <h4>
        <%= @venue.name %>
      </h4>
      <p>
        <%= @venue.address %>
      </p>
    </div>
  </div>
</div>