config/routes.rb
Kite::Application.routes.draw do
  resources :venues
  resources :events do
  	collection do
      delete 'destroy_multiple'
    end
    #member do
  	#	get 'fav'
  	#end
  end
  devise_for :users, :controllers => { :sessions => 'sessions' }
  devise_for :hosts#, :skip => :sessions

  root :to => 'categories#index'
  get 'about' => 'pages#about'
  get 'blog' => 'pages#blog'
  get 'help' => 'pages#help'
  get 'list' => 'events#list'
end

app/views/layouts/_footer.html.erb
<footer>
	<p>Conceptualized and coded in Victoria.</p>
	<ul>
		<li><%= link_to "About", about_path %></li>
		<li><%= link_to "Blog", blog_path %></li>
		<li><%= link_to "Connect", "http://www.twitter.com/hereNowVictoria", :target => "_blank" %></li>
		<li><%= link_to "Help", help_path %></li>
	</ul>
</footer>
<%= javascript_include_tag "application" %>

app/views/layouts/_header.html.erb
<nav class="main-nav">
	<div class="container">
	  <%= navigation_icon %>
	  <%= content_tag(:span, "beta", :class => "beta") if root_path? %> 

		<div class="main-nav-right">
		  <% if user_signed_in? %>
		   	<%= link_to content_tag(:span, " ", :class => "glyphicon glyphicon-cog lg-icon"), edit_user_registration_path %>
		  <% else %>
				<%= link_to "Login", new_user_session_path, :class => "login" %>
			<% end %>
		</div>

		<% if user_signed_in? %>
			<ul class="main-nav-list main-nav-right hidden-xs" role="navigation">
				<% if host_signed_in? %>
					<li><%= link_to "Add Event", new_event_path %></li>
					<li><%= link_to "Add Venue", new_venue_path %></li>
					<li><%= link_to "Manage Events", list_path %></li>
					<li><%= link_to "Manage Venues", venues_path %></li>
				<% end %>
		    <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
		  </ul>
		<% end %>
	</div>
</nav>
<div class="menu-fade"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>hereNow</title>
  <meta name="description" content="Browse things to do in Victoria happening now.">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <link href='http://fonts.googleapis.com/css?family=Roboto:400,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag %>
  <link rel="apple-touch-icon" href="favicon.png" type="image/png" />
  <script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	  ga('create', 'UA-46913597-1', 'herenow.co');
	  ga('send', 'pageview');
	</script>
</head>
<body>
	<%= render 'layouts/header' %>

	<div class="container">
		<% flash.each do |name, msg| %>
	    <%= content_tag(:div, msg, class: "alert alert-#{name}") if msg.length > 0 %>
	  <% end %>

		<%= yield %>
	</div>
	
	<%= render 'layouts/footer' %>
</body>
</html>